### PR TITLE
compiler 0.12 updates with psc-package set

### PR DESCRIPTION
**Pull request by justinwoo**
preliminary PR that updates the library without adding RowToList or anything else, and the tests don't work without a Record Show instance.

### CODE REVIEW

**Comment by paf31** [comment]
Thanks! I have an idea for how to use the `RLRep` idea to implement a efficient `Record` instances too.

**Comment by justinwoo** [comment]
I updated this to remove records. Could add RowToList to this sometime.

**Comment by paf31** [comment]
I made a separate branch with the `Record` changes. I'll make a PR so you can review them and see what you think. It's very similar to this actually.

**Comment by justinwoo** [comment]
Cool, should we close this one? That one looks good

**Comment by paf31** [comment]
Ok will do, thanks anyway!

**Pull request closed without merging**
