### PR TITLE
Map encoding/decoding

### PR DESCRIPTION
**Pull request by jacereda**

### CODE REVIEW

**Comment by paf31** [comment]
Sorry for the delay here.

I like the `StrMap` instances, but I'm not sure how I feel about the `Map` instances. Seems like if someone wants to treat a key like a string, they can use a `StrMap` or a `newtype` around a `Map` fairly easily.

**Comment by jacereda** [comment]
Wouldn't using a `StrMap` be falling in the "stringly typed" side?
As for the `newtype`, do you mean manually writing the `Decode` and `Encode` instances? What would those look like?

**Comment by paf31** [comment]
I think if the data is already a string (like a JSON key) then using the type string is fine. I'm more worried about stringly-typed programming in the sense of using strings for things which shouldn't be strings in the first place (like sum types).

In this case, the user can make a wrapper type whose instance delegates to the `StrMap` instance, since that one implements the most general behavior.

**Comment by jacereda** [comment]
> I'm more worried about stringly-typed programming in the sense of using strings for things which shouldn't be strings in the first place (like sum types).

That's exactly what I want to decode, a map whose key is a sum type. In the original spec the keys are strings, but I prefer to have them as a sum type in my model.

In any case I can probably write the instances manually or maybe handle it generically in a separate library. Closing.

**Pull request closed without merging**
