### PR TITLE
Use generics-rep

### LINKED ISSUE #15: Should this repo support generics-rep?
I was looking at this lib today and I became curious if this repo should support [generics-rep](https://github.com/purescript/purescript-generics-rep). Should it?

### PR DESCRIPTION
**Pull request by paf31**
Fixes #15 

@chexxor Would you mind taking a look over this?

### CODE REVIEW

**Comment by chexxor** [comment]
Requires 0.10.3 compiler? I'm getting an error on `pulp test` for the usage `genericShow`:

```
No type class instance was found for
                                     
    Data.Symbol.IsSymbol "TupleArray"
```

**Comment by paf31** [comment]
Yes, that's right, it needs the symbol deriving feature to derive `Show`.

**Comment by chexxor** [comment]
@paf31 - I'm not sure what exactly you wanted me to check for, so I looked for the bit I'm most interested in seeing fixed in this rewrite, which is adding the missing field name to the error.

It seems to work well in the success case on my one simple test, which is parsing a record, but the failure case still doesn't include the missing field's name. See my notes and test case in my branch, if you're curious: https://github.com/chexxor/purescript-foreign-generic/commit/21ad569fce1e6f2645eb79cf806e6e3f4b078916

I have a suggested fix, but I'm not familiar with the expected return value and errors of the `genericDecodeFieldsField` instance. Following is its description.

`y`, the Foreign value at the expected field name, is 'undefined'. `read undefined` throws error: `(TypeMismatch "String" "Undefined")`. I'd like to add `name`, the field's name, to this error. By doing this, would this function's error message still describe the correct error in all cases of this function args?

**Comment by chexxor** [comment]
Using your suggestion, I added a fix to include the field name. It's in this commit: https://github.com/chexxor/purescript-foreign-generic/commit/c2cf778d631e4a95355ba1bed55858b6d4d967b8#diff-f4f396b6bb00857e2d3c4a669f217589R172

The error message is given a field name like: `(Left (NonEmptyList (NonEmpty (ErrorAtIndex 0 (ErrorAtProperty "name" (TypeMismatch "String" "Undefined"))) Nil)))`

You can pull that fix into your current branch, if you'd like.

**Pull request merged**
